define(function (require, exports, module) {
	var ace = window.ace;

	var lnTools = require("./ext-language_tools");

	require("./ext-searchbox");
	require("./ext-beautify");
	require("./theme-tomorrow_night_eighties");

	var completions = [
		{
			"caption": "0",
			"value": "0",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "1",
			"value": "1",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "grid",
			"value": "grid",
			"score": 108210,
			"metal": "local"
		}, {
			"caption": "series",
			"value": "series",
			"score": 1161721,
			"metal": "local"
		}, {
			"caption": "pie",
			"value": "pie",
			"score": 173151,
			"metal": "local"
		}, {
			"caption": "legend",
			"value": "legend",
			"score": 278319,
			"metal": "local"
		}, {
			"caption": "right",
			"value": "right",
			"score": 12224,
			"metal": "local"
		}, {
			"caption": "tooltip",
			"value": "tooltip",
			"score": 188049,
			"metal": "local"
		}, {
			"caption": "xAxis",
			"value": "xAxis",
			"score": 374619,
			"metal": "local"
		}, {
			"caption": "bar",
			"value": "bar",
			"score": 182040,
			"metal": "local"
		}, {
			"caption": "label",
			"value": "label",
			"score": 163527,
			"metal": "local"
		}, {
			"caption": "emphasis",
			"value": "emphasis",
			"score": 50000,
			"metal": "local"
		}, {
			"caption": "formatter",
			"value": "formatter",
			"score": 62138,
			"metal": "local"
		}, {
			"caption": "line",
			"value": "line",
			"score": 306801,
			"metal": "local"
		}, {
			"caption": "data",
			"value": "data",
			"score": 232156,
			"metal": "local"
		}, {
			"caption": "left",
			"value": "left",
			"score": 24464,
			"metal": "local"
		}, {
			"caption": "top",
			"value": "top",
			"score": 18094,
			"metal": "local"
		}, {
			"caption": "scatter",
			"value": "scatter",
			"score": 48954,
			"metal": "local"
		}, {
			"caption": "type",
			"value": "type",
			"score": 92134,
			"metal": "local"
		}, {
			"caption": "yAxis",
			"value": "yAxis",
			"score": 238764,
			"metal": "local"
		}, {
			"caption": "axisLabel",
			"value": "axisLabel",
			"score": 73604,
			"metal": "local"
		}, {
			"caption": "legendHoverLink",
			"value": "legendHoverLink",
			"score": 14243,
			"metal": "local"
		}, {
			"caption": "textStyle",
			"value": "textStyle",
			"score": 129159,
			"metal": "local"
		}, {
			"caption": "hoverAnimation",
			"value": "hoverAnimation",
			"score": 9062,
			"metal": "local"
		}, {
			"caption": "dataZoom",
			"value": "dataZoom",
			"score": 90999,
			"metal": "local"
		}, {
			"caption": "nameLocation",
			"value": "nameLocation",
			"score": 15800,
			"metal": "local"
		}, {
			"caption": "nameTextStyle",
			"value": "nameTextStyle",
			"score": 30596,
			"metal": "local"
		}, {
			"caption": "nameGap",
			"value": "nameGap",
			"score": 14640,
			"metal": "local"
		}, {
			"caption": "singleAxis",
			"value": "singleAxis",
			"score": 15977,
			"metal": "local"
		}, {
			"caption": "splitLine",
			"value": "splitLine",
			"score": 30047,
			"metal": "local"
		}, {
			"caption": "nameRotate",
			"value": "nameRotate",
			"score": 10483,
			"metal": "local"
		}, {
			"caption": "inverse",
			"value": "inverse",
			"score": 12997,
			"metal": "local"
		}, {
			"caption": "boundaryGap",
			"value": "boundaryGap",
			"score": 18533,
			"metal": "local"
		}, {
			"caption": "clockwise",
			"value": "clockwise",
			"score": 4411,
			"metal": "local"
		}, {
			"caption": "lineStyle",
			"value": "lineStyle",
			"score": 81857,
			"metal": "local"
		}, {
			"caption": "selectedOffset",
			"value": "selectedOffset",
			"score": 2984,
			"metal": "local"
		}, {
			"caption": "width",
			"value": "width",
			"score": 17962,
			"metal": "local"
		}, {
			"caption": "slider",
			"value": "slider",
			"score": 28321,
			"metal": "local"
		}, {
			"caption": "dataBackground",
			"value": "dataBackground",
			"score": 2287,
			"metal": "local"
		}, {
			"caption": "areaStyle",
			"value": "areaStyle",
			"score": 19428,
			"metal": "local"
		}, {
			"caption": "color",
			"value": "color",
			"score": 94439,
			"metal": "local"
		}, {
			"caption": "height",
			"value": "height",
			"score": 7954,
			"metal": "local"
		}, {
			"caption": "orient",
			"value": "orient",
			"score": 17218,
			"metal": "local"
		}, {
			"caption": "align",
			"value": "align",
			"score": 10373,
			"metal": "local"
		}, {
			"caption": "symbol",
			"value": "symbol",
			"score": 35613,
			"metal": "local"
		}, {
			"caption": "xAxisIndex",
			"value": "xAxisIndex",
			"score": 15405,
			"metal": "local"
		}, {
			"caption": "stack",
			"value": "stack",
			"score": 10602,
			"metal": "local"
		}, {
			"caption": "clipOverflow",
			"value": "clipOverflow",
			"score": 3229,
			"metal": "local"
		}, {
			"caption": "center",
			"value": "center",
			"score": 9827,
			"metal": "local"
		}, {
			"caption": "padding",
			"value": "padding",
			"score": 12855,
			"metal": "local"
		}, {
			"caption": "itemStyle",
			"value": "itemStyle",
			"score": 143518,
			"metal": "local"
		}, {
			"caption": "itemGap",
			"value": "itemGap",
			"score": 11914,
			"metal": "local"
		}, {
			"caption": "shadowBlur",
			"value": "shadowBlur",
			"score": 17233,
			"metal": "local"
		}, {
			"caption": "shadowColor",
			"value": "shadowColor",
			"score": 13929,
			"metal": "local"
		}, {
			"caption": "normal",
			"value": "normal",
			"score": 211293,
			"metal": "local"
		}, {
			"caption": "borderColor",
			"value": "borderColor",
			"score": 20648,
			"metal": "local"
		}, {
			"caption": "shadowOffsetX",
			"value": "shadowOffsetX",
			"score": 11499,
			"metal": "local"
		}, {
			"caption": "shadowOffsetY",
			"value": "shadowOffsetY",
			"score": 9210,
			"metal": "local"
		}, {
			"caption": "opacity",
			"value": "opacity",
			"score": 12301,
			"metal": "local"
		}, {
			"caption": "heatmap",
			"value": "heatmap",
			"score": 13825,
			"metal": "local"
		}, {
			"caption": "value",
			"value": "value",
			"score": 21111,
			"metal": "local"
		}, {
			"caption": "fillerColor",
			"value": "fillerColor",
			"score": 797,
			"metal": "local"
		}, {
			"caption": "borderWidth",
			"value": "borderWidth",
			"score": 15576,
			"metal": "local"
		}, {
			"caption": "itemWidth",
			"value": "itemWidth",
			"score": 7123,
			"metal": "local"
		}, {
			"caption": "effectScatter",
			"value": "effectScatter",
			"score": 31179,
			"metal": "local"
		}, {
			"caption": "coordinateSystem",
			"value": "coordinateSystem",
			"score": 15302,
			"metal": "local"
		}, {
			"caption": "axisLine",
			"value": "axisLine",
			"score": 53628,
			"metal": "local"
		}, {
			"caption": "axisTick",
			"value": "axisTick",
			"score": 38765,
			"metal": "local"
		}, {
			"caption": "selectedMode",
			"value": "selectedMode",
			"score": 15177,
			"metal": "local"
		}, {
			"caption": "fontSize",
			"value": "fontSize",
			"score": 14906,
			"metal": "local"
		}, {
			"caption": "inactiveColor",
			"value": "inactiveColor",
			"score": 5720,
			"metal": "local"
		}, {
			"caption": "selected",
			"value": "selected",
			"score": 10921,
			"metal": "local"
		}, {
			"caption": "gauge",
			"value": "gauge",
			"score": 55176,
			"metal": "local"
		}, {
			"caption": "markLine",
			"value": "markLine",
			"score": 65539,
			"metal": "local"
		}, {
			"caption": "handleStyle",
			"value": "handleStyle",
			"score": 1852,
			"metal": "local"
		}, {
			"caption": "borderType",
			"value": "borderType",
			"score": 5717,
			"metal": "local"
		}, {
			"caption": "title",
			"value": "title",
			"score": 158568,
			"metal": "local"
		}, {
			"caption": "show",
			"value": "show",
			"score": 82000,
			"metal": "local"
		}, {
			"caption": "length",
			"value": "length",
			"score": 4814,
			"metal": "local"
		}, {
			"caption": "zlevel",
			"value": "zlevel",
			"score": 22293,
			"metal": "local"
		}, {
			"caption": "labelPrecision",
			"value": "labelPrecision",
			"score": 746,
			"metal": "local"
		}, {
			"caption": "position",
			"value": "position",
			"score": 48349,
			"metal": "local"
		}, {
			"caption": "labelFormatter",
			"value": "labelFormatter",
			"score": 727,
			"metal": "local"
		}, {
			"caption": "alignWithLabel",
			"value": "alignWithLabel",
			"score": 3785,
			"metal": "local"
		}, {
			"caption": "interval",
			"value": "interval",
			"score": 28810,
			"metal": "local"
		}, {
			"caption": "showDetail",
			"value": "showDetail",
			"score": 694,
			"metal": "local"
		}, {
			"caption": "yAxisIndex",
			"value": "yAxisIndex",
			"score": 10560,
			"metal": "local"
		}, {
			"caption": "showDataShadow",
			"value": "showDataShadow",
			"score": 591,
			"metal": "local"
		}, {
			"caption": "realtime",
			"value": "realtime",
			"score": 2611,
			"metal": "local"
		}, {
			"caption": "onZero",
			"value": "onZero",
			"score": 3690,
			"metal": "local"
		}, {
			"caption": "silent",
			"value": "silent",
			"score": 22883,
			"metal": "local"
		}, {
			"caption": "radar",
			"value": "radar",
			"score": 61070,
			"metal": "local"
		}, {
			"caption": "axisPointer",
			"value": "axisPointer",
			"score": 23175,
			"metal": "local"
		}, {
			"caption": "trigger",
			"value": "trigger",
			"score": 15344,
			"metal": "local"
		}, {
			"caption": "barCategoryGap",
			"value": "barCategoryGap",
			"score": 3511,
			"metal": "local"
		}, {
			"caption": "splitNumber",
			"value": "splitNumber",
			"score": 19992,
			"metal": "local"
		}, {
			"caption": "inside",
			"value": "inside",
			"score": 32482,
			"metal": "local"
		}, {
			"caption": "name",
			"value": "name",
			"score": 61072,
			"metal": "local"
		}, {
			"caption": "showSymbol",
			"value": "showSymbol",
			"score": 4778,
			"metal": "local"
		}, {
			"caption": "containLabel",
			"value": "containLabel",
			"score": 6413,
			"metal": "local"
		}, {
			"caption": "offset",
			"value": "offset",
			"score": 15619,
			"metal": "local"
		}, {
			"caption": "max",
			"value": "max",
			"score": 12538,
			"metal": "local"
		}, {
			"caption": "backgroundColor",
			"value": "backgroundColor",
			"score": 32864,
			"metal": "local"
		}, {
			"caption": "visualMap",
			"value": "visualMap",
			"score": 95262,
			"metal": "local"
		}, {
			"caption": "fontStyle",
			"value": "fontStyle",
			"score": 14443,
			"metal": "local"
		}, {
			"caption": "fontWeight",
			"value": "fontWeight",
			"score": 11970,
			"metal": "local"
		}, {
			"caption": "fontFamily",
			"value": "fontFamily",
			"score": 10141,
			"metal": "local"
		}, {
			"caption": "symbolSize",
			"value": "symbolSize",
			"score": 21077,
			"metal": "local"
		}, {
			"caption": "blurSize",
			"value": "blurSize",
			"score": 360,
			"metal": "local"
		}, {
			"caption": "geo",
			"value": "geo",
			"score": 65283,
			"metal": "local"
		}, {
			"caption": "radius",
			"value": "radius",
			"score": 8533,
			"metal": "local"
		}, {
			"caption": "markArea",
			"value": "markArea",
			"score": 19906,
			"metal": "local"
		}, {
			"caption": "map",
			"value": "map",
			"score": 102385,
			"metal": "local"
		}, {
			"caption": "brush",
			"value": "brush",
			"score": 29508,
			"metal": "local"
		}, {
			"caption": "parallel",
			"value": "parallel",
			"score": 20673,
			"metal": "local"
		}, {
			"caption": "parallelAxis",
			"value": "parallelAxis",
			"score": 13713,
			"metal": "local"
		}, {
			"caption": "gridIndex",
			"value": "gridIndex",
			"score": 20650,
			"metal": "local"
		}, {
			"caption": "piecewise",
			"value": "piecewise",
			"score": 25231,
			"metal": "local"
		}, {
			"caption": "showContent",
			"value": "showContent",
			"score": 6960,
			"metal": "local"
		}, {
			"caption": "zoom",
			"value": "zoom",
			"score": 3997,
			"metal": "local"
		}, {
			"caption": "polar",
			"value": "polar",
			"score": 23175,
			"metal": "local"
		}, {
			"caption": "controller",
			"value": "controller",
			"score": 2892,
			"metal": "local"
		}, {
			"caption": "radiusAxis",
			"value": "radiusAxis",
			"score": 24146,
			"metal": "local"
		}, {
			"caption": "angleAxis",
			"value": "angleAxis",
			"score": 18771,
			"metal": "local"
		}, {
			"caption": "toolbox",
			"value": "toolbox",
			"score": 101543,
			"metal": "local"
		}, {
			"caption": "timeline",
			"value": "timeline",
			"score": 34619,
			"metal": "local"
		}, {
			"caption": "precision",
			"value": "precision",
			"score": 3306,
			"metal": "local"
		}, {
			"caption": "curveness",
			"value": "curveness",
			"score": 1378,
			"metal": "local"
		}, {
			"caption": "x",
			"value": "x",
			"score": 2753,
			"metal": "local"
		}, {
			"caption": "valueIndex",
			"value": "valueIndex",
			"score": 2807,
			"metal": "local"
		}, {
			"caption": "itemHeight",
			"value": "itemHeight",
			"score": 5180,
			"metal": "local"
		}, {
			"caption": "icon",
			"value": "icon",
			"score": 10336,
			"metal": "local"
		}, {
			"caption": "valueDim",
			"value": "valueDim",
			"score": 2013,
			"metal": "local"
		}, {
			"caption": "symbolOffset",
			"value": "symbolOffset",
			"score": 10017,
			"metal": "local"
		}, {
			"caption": "y",
			"value": "y",
			"score": 1590,
			"metal": "local"
		}, {
			"caption": "transitionDuration",
			"value": "transitionDuration",
			"score": 3814,
			"metal": "local"
		}, {
			"caption": "radarIndex",
			"value": "radarIndex",
			"score": 715,
			"metal": "local"
		}, {
			"caption": "extraCssText",
			"value": "extraCssText",
			"score": 3640,
			"metal": "local"
		}, {
			"caption": "animation",
			"value": "animation",
			"score": 17864,
			"metal": "local"
		}, {
			"caption": "animationThreshold = 2000",
			"value": "animationThreshold = 2000",
			"score": 11727,
			"metal": "local"
		}, {
			"caption": "minInterval",
			"value": "minInterval",
			"score": 11278,
			"metal": "local"
		}, {
			"caption": "animationDelay",
			"value": "animationDelay",
			"score": 7620,
			"metal": "local"
		}, {
			"caption": "layoutCenter",
			"value": "layoutCenter",
			"score": 2348,
			"metal": "local"
		}, {
			"caption": "animationDurationUpdate",
			"value": "animationDurationUpdate",
			"score": 6972,
			"metal": "local"
		}, {
			"caption": "animationEasingUpdate",
			"value": "animationEasingUpdate",
			"score": 6816,
			"metal": "local"
		}, {
			"caption": "animationDelayUpdate",
			"value": "animationDelayUpdate",
			"score": 6642,
			"metal": "local"
		}, {
			"caption": "symbolRotate",
			"value": "symbolRotate",
			"score": 10221,
			"metal": "local"
		}, {
			"caption": "feature",
			"value": "feature",
			"score": 50238,
			"metal": "local"
		}, {
			"caption": "axis",
			"value": "axis",
			"score": 1794,
			"metal": "local"
		}, {
			"caption": "crossStyle",
			"value": "crossStyle",
			"score": 1830,
			"metal": "local"
		}, {
			"caption": "funnel",
			"value": "funnel",
			"score": 11042,
			"metal": "local"
		}, {
			"caption": "scaleLimit",
			"value": "scaleLimit",
			"score": 4792,
			"metal": "local"
		}, {
			"caption": "roam",
			"value": "roam",
			"score": 7112,
			"metal": "local"
		}, {
			"caption": "itemSize",
			"value": "itemSize",
			"score": 1966,
			"metal": "local"
		}, {
			"caption": "showTitle",
			"value": "showTitle",
			"score": 1851,
			"metal": "local"
		}, {
			"caption": "smooth",
			"value": "smooth",
			"score": 5185,
			"metal": "local"
		}, {
			"caption": "saveAsImage",
			"value": "saveAsImage",
			"score": 9915,
			"metal": "local"
		}, {
			"caption": "showAllSymbol",
			"value": "showAllSymbol",
			"score": 3417,
			"metal": "local"
		}, {
			"caption": "polarIndex",
			"value": "polarIndex",
			"score": 5235,
			"metal": "local"
		}, {
			"caption": "graph",
			"value": "graph",
			"score": 76898,
			"metal": "local"
		}, {
			"caption": "layout",
			"value": "layout",
			"score": 2633,
			"metal": "local"
		}, {
			"caption": "excludeComponents",
			"value": "excludeComponents",
			"score": 447,
			"metal": "local"
		}, {
			"caption": "restore",
			"value": "restore",
			"score": 3693,
			"metal": "local"
		}, {
			"caption": "dataView",
			"value": "dataView",
			"score": 10258,
			"metal": "local"
		}, {
			"caption": "magicType",
			"value": "magicType",
			"score": 10505,
			"metal": "local"
		}, {
			"caption": "iconStyle",
			"value": "iconStyle",
			"score": 9088,
			"metal": "local"
		}, {
			"caption": "nodeScaleRatio",
			"value": "nodeScaleRatio",
			"score": 892,
			"metal": "local"
		}, {
			"caption": "hoverLayerThreshold",
			"value": "hoverLayerThreshold",
			"score": 6480,
			"metal": "local"
		}, {
			"caption": "textAlign",
			"value": "textAlign",
			"score": 9402,
			"metal": "local"
		}, {
			"caption": "splitArea",
			"value": "splitArea",
			"score": 16447,
			"metal": "local"
		}, {
			"caption": "nameMap",
			"value": "nameMap",
			"score": 4584,
			"metal": "local"
		}, {
			"caption": "text",
			"value": "text",
			"score": 11691,
			"metal": "local"
		}, {
			"caption": "pixelRatio",
			"value": "pixelRatio",
			"score": 357,
			"metal": "local"
		}, {
			"caption": "readOnly",
			"value": "readOnly",
			"score": 491,
			"metal": "local"
		}, {
			"caption": "optionToContent",
			"value": "optionToContent",
			"score": 936,
			"metal": "local"
		}, {
			"caption": "lang",
			"value": "lang",
			"score": 549,
			"metal": "local"
		}, {
			"caption": "textareaColor",
			"value": "textareaColor",
			"score": 233,
			"metal": "local"
		}, {
			"caption": "textareaBorderColor",
			"value": "textareaBorderColor",
			"score": 177,
			"metal": "local"
		}, {
			"caption": "option",
			"value": "option",
			"score": 2003,
			"metal": "local"
		}, {
			"caption": "seriesIndex",
			"value": "seriesIndex",
			"score": 4483,
			"metal": "local"
		}, {
			"caption": "back",
			"value": "back",
			"score": 199,
			"metal": "local"
		}, {
			"caption": "rect",
			"value": "rect",
			"score": 323,
			"metal": "local"
		}, {
			"caption": "polygon",
			"value": "polygon",
			"score": 254,
			"metal": "local"
		}, {
			"caption": "min",
			"value": "min",
			"score": 16646,
			"metal": "local"
		}, {
			"caption": "scale",
			"value": "scale",
			"score": 14303,
			"metal": "local"
		}, {
			"caption": "logBase",
			"value": "logBase",
			"score": 7456,
			"metal": "local"
		}, {
			"caption": "start",
			"value": "start",
			"score": 2889,
			"metal": "local"
		}, {
			"caption": "z",
			"value": "z",
			"score": 15867,
			"metal": "local"
		}, {
			"caption": "link",
			"value": "link",
			"score": 5348,
			"metal": "local"
		}, {
			"caption": "textBaseline",
			"value": "textBaseline",
			"score": 4210,
			"metal": "local"
		}, {
			"caption": "subtext",
			"value": "subtext",
			"score": 5086,
			"metal": "local"
		}, {
			"caption": "sublink",
			"value": "sublink",
			"score": 2618,
			"metal": "local"
		}, {
			"caption": "subtarget",
			"value": "subtarget",
			"score": 2373,
			"metal": "local"
		}, {
			"caption": "subtextStyle",
			"value": "subtextStyle",
			"score": 7732,
			"metal": "local"
		}, {
			"caption": "triggerEvent",
			"value": "triggerEvent",
			"score": 9175,
			"metal": "local"
		}, {
			"caption": "blendMode",
			"value": "blendMode",
			"score": 6359,
			"metal": "local"
		}, {
			"caption": "progressiveThreshold",
			"value": "progressiveThreshold",
			"score": 4699,
			"metal": "local"
		}, {
			"caption": "continuous",
			"value": "continuous",
			"score": 42105,
			"metal": "local"
		}, {
			"caption": "lines",
			"value": "lines",
			"score": 31608,
			"metal": "local"
		}, {
			"caption": "markPoint",
			"value": "markPoint",
			"score": 81254,
			"metal": "local"
		}, {
			"caption": "roseType",
			"value": "roseType",
			"score": 4221,
			"metal": "local"
		}, {
			"caption": "animationEasing",
			"value": "animationEasing",
			"score": 8836,
			"metal": "local"
		}, {
			"caption": "animationDuration",
			"value": "animationDuration",
			"score": 9562,
			"metal": "local"
		}, {
			"caption": "calculable",
			"value": "calculable",
			"score": 3953,
			"metal": "local"
		}, {
			"caption": "progressive",
			"value": "progressive",
			"score": 5761,
			"metal": "local"
		}, {
			"caption": "treemap",
			"value": "treemap",
			"score": 16948,
			"metal": "local"
		}, {
			"caption": "links",
			"value": "links",
			"score": 9573,
			"metal": "local"
		}, {
			"caption": "edgeSymbol",
			"value": "edgeSymbol",
			"score": 1211,
			"metal": "local"
		}, {
			"caption": "bottom",
			"value": "bottom",
			"score": 13969,
			"metal": "local"
		}, {
			"caption": "edges",
			"value": "edges",
			"score": 1122,
			"metal": "local"
		}, {
			"caption": "edgeLabel",
			"value": "edgeLabel",
			"score": 1685,
			"metal": "local"
		}, {
			"caption": "edgeSymbolSize",
			"value": "edgeSymbolSize",
			"score": 769,
			"metal": "local"
		}, {
			"caption": "focusNodeAdjacency",
			"value": "focusNodeAdjacency",
			"score": 888,
			"metal": "local"
		}, {
			"caption": "draggable",
			"value": "draggable",
			"score": 965,
			"metal": "local"
		}, {
			"caption": "force",
			"value": "force",
			"score": 5601,
			"metal": "local"
		}, {
			"caption": "geoIndex",
			"value": "geoIndex",
			"score": 2856,
			"metal": "local"
		}, {
			"caption": "circular",
			"value": "circular",
			"score": 1862,
			"metal": "local"
		}, {
			"caption": "avoidLabelOverlap",
			"value": "avoidLabelOverlap",
			"score": 3694,
			"metal": "local"
		}, {
			"caption": "target",
			"value": "target",
			"score": 5476,
			"metal": "local"
		}, {
			"caption": "coord",
			"value": "coord",
			"score": 3995,
			"metal": "local"
		}, {
			"caption": "startValue",
			"value": "startValue",
			"score": 2182,
			"metal": "local"
		}, {
			"caption": "triggerOn",
			"value": "triggerOn",
			"score": 6741,
			"metal": "local"
		}, {
			"caption": "showDelay",
			"value": "showDelay",
			"score": 3535,
			"metal": "local"
		}, {
			"caption": "alwaysShowContent",
			"value": "alwaysShowContent",
			"score": 4928,
			"metal": "local"
		}, {
			"caption": "enterable",
			"value": "enterable",
			"score": 3871,
			"metal": "local"
		}, {
			"caption": "hideDelay",
			"value": "hideDelay",
			"score": 3018,
			"metal": "local"
		}, {
			"caption": "step",
			"value": "step",
			"score": 3437,
			"metal": "local"
		}, {
			"caption": "detail",
			"value": "detail",
			"score": 5434,
			"metal": "local"
		}, {
			"caption": "startAngle",
			"value": "startAngle",
			"score": 5421,
			"metal": "local"
		}, {
			"caption": "handleIcon",
			"value": "handleIcon",
			"score": 1051,
			"metal": "local"
		}, {
			"caption": "handleSize",
			"value": "handleSize",
			"score": 932,
			"metal": "local"
		}, {
			"caption": "zoomLock",
			"value": "zoomLock",
			"score": 1979,
			"metal": "local"
		}, {
			"caption": "throttle",
			"value": "throttle",
			"score": 1757,
			"metal": "local"
		}, {
			"caption": "boxplot",
			"value": "boxplot",
			"score": 6233,
			"metal": "local"
		}, {
			"caption": "candlestick",
			"value": "candlestick",
			"score": 14005,
			"metal": "local"
		}, {
			"caption": "sankey",
			"value": "sankey",
			"score": 10101,
			"metal": "local"
		}, {
			"caption": "loop",
			"value": "loop",
			"score": 678,
			"metal": "local"
		}, {
			"caption": "rewind",
			"value": "rewind",
			"score": 439,
			"metal": "local"
		}, {
			"caption": "controlStyle",
			"value": "controlStyle",
			"score": 1269,
			"metal": "local"
		}, {
			"caption": "labelLine",
			"value": "labelLine",
			"score": 17838,
			"metal": "local"
		}, {
			"caption": "distance",
			"value": "distance",
			"score": 452,
			"metal": "local"
		}, {
			"caption": "rotate",
			"value": "rotate",
			"score": 4666,
			"metal": "local"
		}, {
			"caption": "margin",
			"value": "margin",
			"score": 4342,
			"metal": "local"
		}, {
			"caption": "barWidth",
			"value": "barWidth",
			"score": 6641,
			"metal": "local"
		}, {
			"caption": "category",
			"value": "category",
			"score": 1318,
			"metal": "local"
		}, {
			"caption": "barGap",
			"value": "barGap",
			"score": 4832,
			"metal": "local"
		}, {
			"caption": "nodes",
			"value": "nodes",
			"score": 2085,
			"metal": "local"
		}, {
			"caption": "pieces",
			"value": "pieces",
			"score": 2683,
			"metal": "local"
		}, {
			"caption": "smoothMonotone",
			"value": "smoothMonotone",
			"score": 2203,
			"metal": "local"
		}, {
			"caption": "itemSymbol",
			"value": "itemSymbol",
			"score": 882,
			"metal": "local"
		}, {
			"caption": "axisType",
			"value": "axisType",
			"score": 902,
			"metal": "local"
		}, {
			"caption": "currentIndex",
			"value": "currentIndex",
			"score": 583,
			"metal": "local"
		}, {
			"caption": "effectType",
			"value": "effectType",
			"score": 1364,
			"metal": "local"
		}, {
			"caption": "areaColor",
			"value": "areaColor",
			"score": 2808,
			"metal": "local"
		}, {
			"caption": "showEffectOn",
			"value": "showEffectOn",
			"score": 1285,
			"metal": "local"
		}, {
			"caption": "rippleEffect",
			"value": "rippleEffect",
			"score": 3617,
			"metal": "local"
		}, {
			"caption": "minAngle",
			"value": "minAngle",
			"score": 2527,
			"metal": "local"
		}, {
			"caption": "barMaxWidth",
			"value": "barMaxWidth",
			"score": 3073,
			"metal": "local"
		}, {
			"caption": "rotateLabel",
			"value": "rotateLabel",
			"score": 523,
			"metal": "local"
		}, {
			"caption": "dimension",
			"value": "dimension",
			"score": 1922,
			"metal": "local"
		}, {
			"caption": "end",
			"value": "end",
			"score": 1426,
			"metal": "local"
		}, {
			"caption": "inRange",
			"value": "inRange",
			"score": 4604,
			"metal": "local"
		}, {
			"caption": "outOfRange",
			"value": "outOfRange",
			"score": 2262,
			"metal": "local"
		}, {
			"caption": "checkpointStyle",
			"value": "checkpointStyle",
			"score": 1036,
			"metal": "local"
		}, {
			"caption": "sampling",
			"value": "sampling",
			"score": 2458,
			"metal": "local"
		}, {
			"caption": "regions",
			"value": "regions",
			"score": 6273,
			"metal": "local"
		}, {
			"caption": "large",
			"value": "large",
			"score": 1055,
			"metal": "local"
		}, {
			"caption": "showLegendSymbol",
			"value": "showLegendSymbol",
			"score": 1600,
			"metal": "local"
		}, {
			"caption": "layoutSize",
			"value": "layoutSize",
			"score": 1981,
			"metal": "local"
		}, {
			"caption": "mapValueCalculation",
			"value": "mapValueCalculation",
			"score": 1447,
			"metal": "local"
		}, {
			"caption": "categories",
			"value": "categories",
			"score": 4362,
			"metal": "local"
		}, {
			"caption": "indicator",
			"value": "indicator",
			"score": 2995,
			"metal": "local"
		}, {
			"caption": "barBorderRadius",
			"value": "barBorderRadius",
			"score": 1455,
			"metal": "local"
		}, {
			"caption": "range",
			"value": "range",
			"score": 2009,
			"metal": "local"
		}, {
			"caption": "connectNulls",
			"value": "connectNulls",
			"score": 3411,
			"metal": "local"
		}, {
			"caption": "pointer",
			"value": "pointer",
			"score": 2665,
			"metal": "local"
		}, {
			"caption": "effect",
			"value": "effect",
			"score": 5446,
			"metal": "local"
		}, {
			"caption": "parallelAxisDefault",
			"value": "parallelAxisDefault",
			"score": 927,
			"metal": "local"
		}, {
			"caption": "coords",
			"value": "coords",
			"score": 750,
			"metal": "local"
		}, {
			"caption": "shadowStyle",
			"value": "shadowStyle",
			"score": 1670,
			"metal": "local"
		}, {
			"caption": "largeThreshold",
			"value": "largeThreshold",
			"score": 754,
			"metal": "local"
		}, {
			"caption": "hoverLink",
			"value": "hoverLink",
			"score": 1276,
			"metal": "local"
		}, {
			"caption": "repulsion",
			"value": "repulsion",
			"score": 865,
			"metal": "local"
		}, {
			"caption": "textGap",
			"value": "textGap",
			"score": 1121,
			"metal": "local"
		}, {
			"caption": "breadcrumb",
			"value": "breadcrumb",
			"score": 828,
			"metal": "local"
		}, {
			"caption": "baseline",
			"value": "baseline",
			"score": 1316,
			"metal": "local"
		}, {
			"caption": "endAngle",
			"value": "endAngle",
			"score": 895,
			"metal": "local"
		}, {
			"caption": "period",
			"value": "period",
			"score": 1153,
			"metal": "local"
		}, {
			"caption": "brushType",
			"value": "brushType",
			"score": 1421,
			"metal": "local"
		}, {
			"caption": "minOpacity",
			"value": "minOpacity",
			"score": 216,
			"metal": "local"
		}, {
			"caption": "brushLink",
			"value": "brushLink",
			"score": 913,
			"metal": "local"
		}, {
			"caption": "brushMode",
			"value": "brushMode",
			"score": 465,
			"metal": "local"
		}, {
			"caption": "transformable",
			"value": "transformable",
			"score": 418,
			"metal": "local"
		}, {
			"caption": "brushStyle",
			"value": "brushStyle",
			"score": 507,
			"metal": "local"
		}, {
			"caption": "throttleType",
			"value": "throttleType",
			"score": 448,
			"metal": "local"
		}, {
			"caption": "throttleDelay",
			"value": "throttleDelay",
			"score": 369,
			"metal": "local"
		}, {
			"caption": "removeOnClick",
			"value": "removeOnClick",
			"score": 648,
			"metal": "local"
		}, {
			"caption": "inBrush",
			"value": "inBrush",
			"score": 500,
			"metal": "local"
		}, {
			"caption": "outOfBrush",
			"value": "outOfBrush",
			"score": 466,
			"metal": "local"
		}, {
			"caption": "offsetCenter",
			"value": "offsetCenter",
			"score": 981,
			"metal": "local"
		}, {
			"caption": "barMinHeight",
			"value": "barMinHeight",
			"score": 2279,
			"metal": "local"
		}, {
			"caption": "parallelIndex",
			"value": "parallelIndex",
			"score": 235,
			"metal": "local"
		}, {
			"caption": "nodeClick",
			"value": "nodeClick",
			"score": 732,
			"metal": "local"
		}, {
			"caption": "source",
			"value": "source",
			"score": 869,
			"metal": "local"
		}, {
			"caption": "color0",
			"value": "color0",
			"score": 210,
			"metal": "local"
		}, {
			"caption": "filterMode",
			"value": "filterMode",
			"score": 2252,
			"metal": "local"
		}, {
			"caption": "tiled",
			"value": "tiled",
			"score": 352,
			"metal": "local"
		}, {
			"caption": "autoPlay",
			"value": "autoPlay",
			"score": 496,
			"metal": "local"
		}, {
			"caption": "playInterval",
			"value": "playInterval",
			"score": 440,
			"metal": "local"
		}, {
			"caption": "sort",
			"value": "sort",
			"score": 484,
			"metal": "local"
		}, {
			"caption": "polyline",
			"value": "polyline",
			"score": 929,
			"metal": "local"
		}, {
			"caption": "initLayout",
			"value": "initLayout",
			"score": 966,
			"metal": "local"
		}, {
			"caption": "controlPosition",
			"value": "controlPosition",
			"score": 408,
			"metal": "local"
		}, {
			"caption": "children",
			"value": "children",
			"score": 89,
			"metal": "local"
		}, {
			"caption": "contentToOption",
			"value": "contentToOption",
			"score": 590,
			"metal": "local"
		}, {
			"caption": "maxOpacity",
			"value": "maxOpacity",
			"score": 215,
			"metal": "local"
		}, {
			"caption": "squareRatio",
			"value": "squareRatio",
			"score": 281,
			"metal": "local"
		}, {
			"caption": "leafDepth",
			"value": "leafDepth",
			"score": 347,
			"metal": "local"
		}, {
			"caption": "zoomToNodeRatio",
			"value": "zoomToNodeRatio",
			"score": 300,
			"metal": "local"
		}, {
			"caption": "childrenVisibleMin",
			"value": "childrenVisibleMin",
			"score": 303,
			"metal": "local"
		}, {
			"caption": "shape",
			"value": "shape",
			"score": 1054,
			"metal": "local"
		}, {
			"caption": "length2",
			"value": "length2",
			"score": 891,
			"metal": "local"
		}, {
			"caption": "endValue",
			"value": "endValue",
			"score": 1107,
			"metal": "local"
		}, {
			"caption": "gravity",
			"value": "gravity",
			"score": 634,
			"metal": "local"
		}, {
			"caption": "edgeLength",
			"value": "edgeLength",
			"score": 662,
			"metal": "local"
		}, {
			"caption": "layoutAnimation",
			"value": "layoutAnimation",
			"score": 485,
			"metal": "local"
		}, {
			"caption": "colorAlpha",
			"value": "colorAlpha",
			"score": 389,
			"metal": "local"
		}, {
			"caption": "constantSpeed",
			"value": "constantSpeed",
			"score": 451,
			"metal": "local"
		}, {
			"caption": "trailLength",
			"value": "trailLength",
			"score": 530,
			"metal": "local"
		}, {
			"caption": "dim",
			"value": "dim",
			"score": 313,
			"metal": "local"
		}, {
			"caption": "areaSelectStyle",
			"value": "areaSelectStyle",
			"score": 253,
			"metal": "local"
		}, {
			"caption": "funnelAlign",
			"value": "funnelAlign",
			"score": 334,
			"metal": "local"
		}, {
			"caption": "buttonTextColor",
			"value": "buttonTextColor",
			"score": 177,
			"metal": "local"
		}, {
			"caption": "buttonColor",
			"value": "buttonColor",
			"score": 205,
			"metal": "local"
		}, {
			"caption": "levels",
			"value": "levels",
			"score": 2267,
			"metal": "local"
		}, {
			"caption": "textColor",
			"value": "textColor",
			"score": 178,
			"metal": "local"
		}, {
			"caption": "lineX",
			"value": "lineX",
			"score": 46,
			"metal": "local"
		}, {
			"caption": "lineY",
			"value": "lineY",
			"score": 32,
			"metal": "local"
		}, {
			"caption": "showPlayBtn",
			"value": "showPlayBtn",
			"score": 64,
			"metal": "local"
		}, {
			"caption": "showPrevBtn",
			"value": "showPrevBtn",
			"score": 43,
			"metal": "local"
		}, {
			"caption": "showNextBtn",
			"value": "showNextBtn",
			"score": 43,
			"metal": "local"
		}, {
			"caption": "playIcon",
			"value": "playIcon",
			"score": 90,
			"metal": "local"
		}, {
			"caption": "stopIcon",
			"value": "stopIcon",
			"score": 48,
			"metal": "local"
		}, {
			"caption": "prevIcon",
			"value": "prevIcon",
			"score": 39,
			"metal": "local"
		}, {
			"caption": "nextIcon",
			"value": "nextIcon",
			"score": 36,
			"metal": "local"
		}, {
			"caption": "ellipsis",
			"value": "ellipsis",
			"score": 76,
			"metal": "local"
		}, {
			"caption": "clear",
			"value": "clear",
			"score": 114,
			"metal": "local"
		}, {
			"caption": "colorMappingBy",
			"value": "colorMappingBy",
			"score": 424,
			"metal": "local"
		}, {
			"caption": "maxSize",
			"value": "maxSize",
			"score": 131,
			"metal": "local"
		}, {
			"caption": "minSize",
			"value": "minSize",
			"score": 147,
			"metal": "local"
		}, {
			"caption": "gap",
			"value": "gap",
			"score": 175,
			"metal": "local"
		}, {
			"caption": "visibleMin",
			"value": "visibleMin",
			"score": 315,
			"metal": "local"
		}, {
			"caption": "axisExpandable",
			"value": "axisExpandable",
			"score": 134,
			"metal": "local"
		}, {
			"caption": "layoutIterations",
			"value": "layoutIterations",
			"score": 226,
			"metal": "local"
		}, {
			"caption": "nodeGap",
			"value": "nodeGap",
			"score": 158,
			"metal": "local"
		}, {
			"caption": "nodeWidth",
			"value": "nodeWidth",
			"score": 134,
			"metal": "local"
		}, {
			"caption": "axisExpandCenter",
			"value": "axisExpandCenter",
			"score": 79,
			"metal": "local"
		}, {
			"caption": "axisExpandCount",
			"value": "axisExpandCount",
			"score": 56,
			"metal": "local"
		}, {
			"caption": "axisExpandWidth",
			"value": "axisExpandWidth",
			"score": 51,
			"metal": "local"
		}, {
			"caption": "boxWidth",
			"value": "boxWidth",
			"score": 46,
			"metal": "local"
		}, {
			"caption": "gapWidth",
			"value": "gapWidth",
			"score": 78,
			"metal": "local"
		}, {
			"caption": "borderColorSaturation",
			"value": "borderColorSaturation",
			"score": 56,
			"metal": "local"
		}, {
			"caption": "inactiveOpacity",
			"value": "inactiveOpacity",
			"score": 51,
			"metal": "local"
		}, {
			"caption": "keep",
			"value": "keep",
			"score": 41,
			"metal": "local"
		}, {
			"caption": "colorSaturation",
			"value": "colorSaturation",
			"score": 343,
			"metal": "local"
		}, {
			"caption": "visualDimension",
			"value": "visualDimension",
			"score": 471,
			"metal": "local"
		}, {
			"caption": "id",
			"value": "id",
			"score": 138,
			"metal": "local"
		}, {
			"caption": "borderColor0",
			"value": "borderColor0",
			"score": 67,
			"metal": "local"
		}, {
			"caption": "emptyItemWidth",
			"value": "emptyItemWidth",
			"score": 60,
			"metal": "local"
		}, {
			"caption": "activeOpacity",
			"value": "activeOpacity",
			"score": 43,
			"metal": "local"
		}, {
			"caption": "radiusAxisIndex",
			"value": "radiusAxisIndex",
			"score": 574,
			"metal": "local"
		}, {
			"caption": "angleAxisIndex",
			"value": "angleAxisIndex",
			"score": 478,
			"metal": "local"
		}, {
			"caption": "textPosition",
			"value": "textPosition",
			"score": 232,
			"metal": "local"
		}, {
			"caption": "minOpen",
			"value": "minOpen",
			"score": 194,
			"metal": "local"
		}, {
			"caption": "maxOpen",
			"value": "maxOpen",
			"score": 125,
			"metal": "local"
		}, {
			"caption": "graphic",
			"value": "graphic",
			"score": 5617,
			"metal": "local"
		}, {
			"caption": "elements",
			"value": "elements",
			"score": 3108,
			"metal": "local"
		}, {
			"caption": "image",
			"value": "image",
			"score": 673,
			"metal": "local"
		}, {
			"caption": "group",
			"value": "group",
			"score": 488,
			"metal": "local"
		}, {
			"caption": "$action",
			"value": "$action",
			"score": 82,
			"metal": "local"
		}, {
			"caption": "style",
			"value": "style",
			"score": 431,
			"metal": "local"
		}, {
			"caption": "textVerticalAlign",
			"value": "textVerticalAlign",
			"score": 13,
			"metal": "local"
		}, {
			"caption": "fill",
			"value": "fill",
			"score": 55,
			"metal": "local"
		}, {
			"caption": "stroke",
			"value": "stroke",
			"score": 47,
			"metal": "local"
		}, {
			"caption": "lineWidth",
			"value": "lineWidth",
			"score": 34,
			"metal": "local"
		}, {
			"caption": "sector",
			"value": "sector",
			"score": 93,
			"metal": "local"
		}, {
			"caption": "bezier-curve",
			"value": "bezier-curve",
			"score": 6,
			"metal": "local"
		}, {
			"caption": "cpx2",
			"value": "cpx2",
			"score": 1,
			"metal": "local"
		}, {
			"caption": "cpy2",
			"value": "cpy2",
			"score": 1,
			"metal": "local"
		}, {
			"caption": "circle",
			"value": "circle",
			"score": 256,
			"metal": "local"
		}, {
			"caption": "arc",
			"value": "arc",
			"score": 61,
			"metal": "local"
		}, {
			"caption": "bezierCurve",
			"value": "bezierCurve",
			"score": 61,
			"metal": "local"
		}, {
			"caption": "onclick",
			"value": "onclick",
			"score": 101,
			"metal": "local"
		}, {
			"caption": "onmouseover",
			"value": "onmouseover",
			"score": 32,
			"metal": "local"
		}, {
			"caption": "font",
			"value": "font",
			"score": 17,
			"metal": "local"
		}, {
			"caption": "bounding",
			"value": "bounding",
			"score": 75,
			"metal": "local"
		}, {
			"caption": "cursor",
			"value": "cursor",
			"score": 54,
			"metal": "local"
		}, {
			"caption": "themeRiver",
			"value": "themeRiver",
			"score": 11,
			"metal": "local"
		}, {
			"caption": "confine",
			"value": "confine",
			"score": 580,
			"metal": "local"
		}, {
			"caption": "ring",
			"value": "ring",
			"score": 103,
			"metal": "local"
		}, {
			"caption": "ondragleave",
			"value": "ondragleave",
			"score": 3,
			"metal": "local"
		}, {
			"caption": "ondragstart",
			"value": "ondragstart",
			"score": 4,
			"metal": "local"
		}, {
			"caption": "ondragover",
			"value": "ondragover",
			"score": 4,
			"metal": "local"
		}, {
			"caption": "disabled",
			"value": "disabled",
			"score": 221,
			"metal": "local"
		}, {
			"caption": "visualMin",
			"value": "visualMin",
			"score": 44,
			"metal": "local"
		}, {
			"caption": "visualMax",
			"value": "visualMax",
			"score": 18,
			"metal": "local"
		}, {
			"caption": "onmousemove",
			"value": "onmousemove",
			"score": 14,
			"metal": "local"
		}, {
			"caption": "ondrag",
			"value": "ondrag",
			"score": 8,
			"metal": "local"
		}, {
			"caption": "ondragend",
			"value": "ondragend",
			"score": 2,
			"metal": "local"
		}, {
			"caption": "x2",
			"value": "x2",
			"score": 7,
			"metal": "local"
		}, {
			"caption": "x1",
			"value": "x1",
			"score": 4,
			"metal": "local"
		}, {
			"caption": "y1",
			"value": "y1",
			"score": 2,
			"metal": "local"
		}, {
			"caption": "y2",
			"value": "y2",
			"score": 3,
			"metal": "local"
		}, {
			"caption": "percent",
			"value": "percent",
			"score": 6,
			"metal": "local"
		}, {
			"caption": "ondrop",
			"value": "ondrop",
			"score": 9,
			"metal": "local"
		}, {
			"caption": "cx",
			"value": "cx",
			"score": 7,
			"metal": "local"
		}, {
			"caption": "smoothConstraint",
			"value": "smoothConstraint",
			"score": 20,
			"metal": "local"
		}, {
			"caption": "cpx1",
			"value": "cpx1",
			"score": 2,
			"metal": "local"
		}, {
			"caption": "points",
			"value": "points",
			"score": 16,
			"metal": "local"
		}, {
			"caption": "onmousewheel",
			"value": "onmousewheel",
			"score": 13,
			"metal": "local"
		}, {
			"caption": "onmouseout",
			"value": "onmouseout",
			"score": 7,
			"metal": "local"
		}, {
			"caption": "barBorderWidth",
			"value": "barBorderWidth",
			"score": 2,
			"metal": "local"
		}, {
			"caption": "ondragenter",
			"value": "ondragenter",
			"score": 2,
			"metal": "local"
		}, {
			"caption": "onmouseup",
			"value": "onmouseup",
			"score": 1,
			"metal": "local"
		}, {
			"caption": "cy",
			"value": "cy",
			"score": 1,
			"metal": "local"
		}, {
			"caption": "r",
			"value": "r",
			"score": 2,
			"metal": "local"
		}, {
			"caption": "onmousedown",
			"value": "onmousedown",
			"score": 1,
			"metal": "local"
		}, {
			"caption": "animationThreshold",
			"value": "animationThreshold",
			"score": 1,
			"metal": "local"
		}, {
			"caption": "snap",
			"value": "snap",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "showMinLabel",
			"value": "showMinLabel",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "showMaxLabel",
			"value": "showMaxLabel",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "tiggerTooltip",
			"value": "tiggerTooltip",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "status",
			"value": "status",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "handle",
			"value": "handle",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "size",
			"value": "size",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "minSpan",
			"value": "minSpan",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "maxSpan",
			"value": "maxSpan",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "minValueSpan",
			"value": "minValueSpan",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "maxValueSpan",
			"value": "maxValueSpan",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "showLabel",
			"value": "showLabel",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "aspectScale",
			"value": "aspectScale",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "boundingCoords",
			"value": "boundingCoords",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "axisExpandTriggerOn",
			"value": "axisExpandTriggerOn",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "invisible",
			"value": "invisible",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "r0",
			"value": "r0",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "cpy1",
			"value": "cpy1",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "calendar",
			"value": "calendar",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "cellSize",
			"value": "cellSize",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "dayLabel",
			"value": "dayLabel",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "firstDay",
			"value": "firstDay",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "monthLabel",
			"value": "monthLabel",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "yearLabel",
			"value": "yearLabel",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "stillShowZeroSum",
			"value": "stillShowZeroSum",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "animationType",
			"value": "animationType",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "barMinWidth",
			"value": "barMinWidth",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "delay",
			"value": "delay",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "symbolPosition",
			"value": "symbolPosition",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "symbolRepeat",
			"value": "symbolRepeat",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "symbolRepeatDirection",
			"value": "symbolRepeatDirection",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "symbolMargin",
			"value": "symbolMargin",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "symbolClip",
			"value": "symbolClip",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "symbolBoundingData",
			"value": "symbolBoundingData",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "symbolPatternSize",
			"value": "symbolPatternSize",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "singleAxisIndex",
			"value": "singleAxisIndex",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "date",
			"value": "date",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "useUTC",
			"value": "useUTC",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "FireBird",
			"value": "FireBird",
			"score": 0,
			"metal": "local"
		}, {
			"caption": "lodash",
			"value": "lodash",
			"score": 0,
			"metal": "local"
		},{
			"caption": "dayjs",
			"value": "dayjs",
			"score": 0,
			"metal": "local"
		},{
			"caption": "jQuery",
			"value": "jQuery",
			"score": 0,
			"metal": "local"
		},{
			"caption": "$",
			"value": "$",
			"score": 0,
			"metal": "local"
		},{
			"caption": "_",
			"value": "_",
			"score": 0,
			"metal": "local"
		},{
			"caption": "screen",
			"value": "screen",
			"score": 0,
			"metal": "local"
		},{
			"caption": "SockJs",
			"value": "SockJs",
			"score": 0,
			"metal": "local"
		},{
			"caption": "setOptionsById",
			"value": "setOptionsById",
			"score": 0,
			"metal": "local" ,
			"getDocTooltip": ""
		},{
			"caption": "this.$chart.setOption",
			"value": "this.$chart.setOption",
			"score": 0,
			"metal": "local" ,
			"getDocTooltip": "this.$chart.setOption(option)"
		},{
			"caption": "this.$chart.getOption",
			"value": "this.$chart.getOption",
			"score": 0,
			"metal": "local" ,
			"getDocTooltip": "this.$chart.getOption()"
		},{
			"caption": "this.$chart 图表实例",
			"value": "this.$chart",
			"score": 0,
			"metal": "local" ,
			"getDocTooltip": "this.$chart"
		},


		{
			"caption": "this.$root.setOptionsById(id, {})",
			"value": "this.$root.setOptionsById(id, {})",
			"score": 0,
			"metal": "local" ,
			"getDocTooltip": "this.$root.setOptionsById(id, {</br>})"
		},



	];



	lnTools.addCompleter({
		getCompletions: function (e, t, o, n, a) {
			a(null, completions)
		}
	});

	module.exports = window.ace

});




